DROP SEQUENCE if exists seq_func;

CREATE SEQUENCE seq_func START WITH 1 INCREMENT BY 10;

DROP SEQUENCE if exists seq_cargo;

CREATE SEQUENCE seq_cargo START WITH 1 INCREMENT BY 10;

DROP SEQUENCE if exists seq_depto;

CREATE SEQUENCE  seq_depto START WITH 1 INCREMENT BY 10;

DROP SEQUENCE if exists seq_historico;

CREATE SEQUENCE seq_historico START WITH 1 INCREMENT BY 10;

INSERT INTO CARGO(CARGO_ID,CARGO_NAME) VALUES(NEXT VALUE FOR SEQ_CARGO, 'PROGRAMADOR');

INSERT INTO CARGO(CARGO_ID,CARGO_NAME) VALUES(NEXT VALUE FOR SEQ_CARGO, 'TESTER');

INSERT INTO CARGO(CARGO_ID,CARGO_NAME) VALUES(NEXT VALUE FOR SEQ_CARGO, 'GERENTE');

INSERT INTO DEPARTAMENTO(DEPARTAMENTO_ID, DEPARTAMENTO_NAME) VALUES (NEXT VALUE FOR SEQ_DEPTO, 'Administracao');

INSERT INTO DEPARTAMENTO(DEPARTAMENTO_ID, DEPARTAMENTO_NAME) VALUES (NEXT VALUE FOR SEQ_DEPTO, 'Projetos');

INSERT INTO DEPARTAMENTO(DEPARTAMENTO_ID, DEPARTAMENTO_NAME) VALUES (NEXT VALUE FOR SEQ_DEPTO, 'Infraestrutura');